name: Sentry
on:
  release:
    types:
      - released
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.action != 'deleted' && "${{ github.repository }}" == 'Reetus/ClassicAssist'
    steps:
      - name: Release Info Action
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: Reetus
          repo: ClassicAssist
      - uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          echo LATEST="${{ steps.latest_version.outputs.latest_tag }}+${{ steps.latest_version.outputs.target_commitish }}" >> $GITHUB_ENV
      - name: Show Version
        run: echo $LATEST
      - name: Create Sentry release
        env:
          LATEST: ${{ env.LATEST }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_LOG_LEVEL: info
        uses: getsentry/action-release@v1
        with:
          version: ${{ env.LATEST }}
          environment: production
