name: Update Wiki
permissions:
  contents:
    write
on:
  release:
    types:
      - released
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    if: |
      (github.event_name == 'release' &&
      github.event.release.prerelease == false &&
      github.event.action != 'deleted') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/checkout@v5
      with:
        repository: ${{ github.repository }}.wiki
        fetch-depth: 0
        path: ${{ github.event.repository.name }}.wiki
    - name: Set version
      id: version
      run: |
          echo "VERSION=$(git describe --tags --abbrev=0 --match="[0-9]*.[0-9]*.[0-9]*")" >> $env:GITHUB_ENV
    - name: Checkout Tag
      run: git checkout $env:VERSION
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Build ClassicAssist.dll
      run: dotnet build .\ClassicAssist\ClassicAssist.csproj /p:Version=$env:VERSION
    - name: Build ExportCommands
      run: dotnet build .\Tools\ExportCommands\ExportCommands.csproj
    - name: Generate Docs
      run: |
          cd Output\net48
          $fullPath = (Get-Location).Path
          .\ExportCommands.exe $fullPath\ClassicAssist.dll
    - name: Update Wiki
      run: |
          git config --global user.email "actions@localhost"
          git config --global user.name "Update Wiki Action"
          cd ${{ github.event.repository.name }}.wiki
          copy ..\Output\net48\Docs\*.md .
          git add *
          git commit -m "Update Wiki"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          git push
